import type { Metadata, NextPage } from 'next';
import type { PropsWithChildren } from 'react';
import { Work_Sans } from 'next/font/google'
import { Header, Footer } from '../../features';
import './globals.css'

const workSans = Work_Sans({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
    title: 'Flexibble',
    description: 'Generated by create next app',
};

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {

    return (
        <html lang='ko'>
            <body className={workSans.className}>
                <div className='flex flex-col items-center min-h-screen bg-gradient-to-r from-green-200 to-blue-300'>
                    <Header />
                    <div className='flex-1'>
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}

export default RootLayout;